
DATA_TRANSFORMATION_DIR: str = "data_transformation"
DATA_TRANSFORMATION_PIPELINE_DIR: str= "transformed_pipeline"
DATA_TRANSFORMATION_TRAIN_DIR: str = "train"
DATA_TRANSFORMATION_FILE_NAME: str = "finance_complaint"
DATA_TRANSFORMATION_TEST_DIR: str = "test"
DATA_TRANSFORMATION_TEST_SIZE: float = 0.3